[package]
distribution = "2201.3.0"
org= "ballerinax"
name= "slack"
version= "3.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Communication/Team Chat", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-slack"
